# Projeto acadêmico - Chat com RabbitMQ
# As configurações não utilizam variáveis de ambiente,
# pois o sistema será executado apenas em ambiente local (localhost).

spring.application.name=chat-rabbitmQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672

logging.level.org.springframework=ERROR